// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c6a5b70e-a1f8-444a-8bb7-824f563f4894",
    "aws_cognito_region": "ap-south-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "8ee0a40b80334a8092931f270ff95c3c",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
